import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    already: {
        fontSize: 16,
        marginTop: '9%',
        color: '#FF69B4',
        fontWeight: 'bold',
        textShadowRadius: 1,
        textShadowOffset: { width: 1, height: 1 },
        textShadowColor: 'black',
    },
    alreadyBtnText: {
        color: '#1dacd6',
        fontSize: 16,
        fontWeight: 'bold',
        textShadowRadius: .5,
        textShadowOffset: { width: .7, height: .7 },
        textShadowColor: 'black',
        marginLeft: '2%',
        marginTop: '9%',
        paddingLeft: 2,
        textDecorationLine: 'underline',
    },
    backColor: {
        backgroundColor: '#f6f6f6',
        alignItems: 'center'
    },
    button: {
        borderWidth: 4,
        borderColor: '#1dacd6',
        alignSelf: 'center',
        backgroundColor: '#1dacd6',
        borderRadius: 50,
        marginTop: 20,
    },
    buttonText: {
        color: '#FF69B4',
        textShadowRadius: 1,
        textShadowOffset: { width: 0, height: 1 },
        textShadowColor: 'black',
        alignSelf: 'center',
        paddingTop: '4.5%',
        fontWeight: 'bold',
    },
    btnText: {
        color: 'white',
        fontSize: 18,
        marginVertical: 5,
        marginHorizontal: 20,
        fontWeight: 'bold',
        textShadowRadius: 3,
        textShadowOffset: { width: 1, height: 1 },
        textShadowColor: '#FF69B4',
    },
    feedback: {
        alignSelf: 'center',
        fontWeight: 'bold',
        color: '#FF69B4',
        fontSize: 22,
        textShadowRadius: 1,
        textShadowOffset: { width: 1, height: 1 },
        textShadowColor: 'black',
    },
    flexCenter: {
        display: 'flex',
        justifyContent: 'center',
        flex: 1,
    },
    inputMessage: {
        width: '75%',
        height: 100,
        borderColor: '#1dacd6',
        borderWidth: 2,
        marginLeft: '10%',
        marginBottom: 30,
    },
    name: {
        color: '#FF69B4',
        fontWeight: 'bold',
        fontSize: 30,
        textAlign: 'center',
        textShadowRadius: 2,
        textShadowOffset: { width: 1, height: 1 },
        textShadowColor: 'black',
    },
    opac: {
        borderWidth: 2,
        backgroundColor: 'white',
        borderColor: '#FF69B4',
        borderRadius: 10,
        height: 40,
        width: 225,
        marginTop: 15,
    },
    opac_last: {
        borderWidth: 2,
        backgroundColor: 'white',
        borderColor: '#FF69B4',
        borderRadius: 10,
        height: 40,
        width: 225,
        marginVertical: 15,
    },
    photo: {
        height: 180,
        width: 180,
        marginTop: '15%',
        marginBottom: 10,
        borderRadius: 100,
    },
    resourceBlock: {
        backgroundColor: '#FF69B4',
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        margin: 10,
        padding: 5,
    },
    resourceText: {
        color: 'black',
        textShadowColor: '#FFB6DA',
        textShadowOffset: { width: 5, height: 5 },
        textShadowRadius: 50,
        margin: 10,
        fontSize: 15,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    resourceTitle: {
        color: 'black',
        fontWeight: 'bold',
        fontSize: 22,
        textAlign: 'center',
        textShadowColor: '#FFB6DA',
        textShadowOffset: { width: 5, height: 3 },
        textShadowRadius: 2,
        marginTop: 22,
        marginBottom: 5,
    },
    secondaryResourceText: {
        color: '#f5f5f5',
        fontStyle: 'italic',
        textDecorationColor: '#7AD7F0',
        textDecorationLine: 'underline',
        textDecorationStyle: 'solid',
        textShadowRadius: 2,
        margin: 10,
        fontSize: 17,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    signin: {
        flexDirection: 'row',
        justifyContent: 'center'
    },
    text: {
        fontSize: 18,
        marginLeft: '10%',
        marginBottom: '2%',
        color: '#FF69B4',
        fontWeight: 'bold',
        textShadowRadius: 1,
        textShadowOffset: { width: 1, height: 1 },
        textShadowColor: 'black',
    },
    textMargin: {
        marginTop: '15%',
    },
    textInput: {
        width: '75%',
        height: 30,
        borderColor: '#1dacd6',
        borderWidth: 2,
        marginLeft: '10%',
        marginBottom: '8%',
    },
});